name: A workflow for group 16 CW App
on:
  push:
    branches: [ master, develop ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - '**/*.sql'

jobs:

  IntegrationTests:
    name: Unit and Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run database docker container
        run: |
          docker build -t db ./db
          docker run --name worldDb --hostname db -dp 3306:3306 db
      - name: Unit and integration tests
        #run: mvn -Dtest=com.napier.sem.* test
        run: mvn clean test jacoco:report
      - name: Stop database docker container
        run: |
          docker stop worldDb
          docker rm worldDb
          docker image rm db

      - name: Update CodeCov reports
        #uses: codecov/codecov-action@v4.0.1
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)
          slug: stevecastillonapier/Group16Devops

  build:
    name: mysql and java Sample Report workflow
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar
